#!/usr/bin/env node
/**
 * Generate the PWA icon set from public/icons/icon.svg (A1 — "Mosaic O · Clean").
 *
 *   icon-192.png            standard manifest icon
 *   icon-512.png            standard manifest icon
 *   icon-maskable-512.png   maskable variant (full-bleed cream — no rounded
 *                           corners so the OS can crop to circle/squircle
 *                           without revealing transparent edges)
 *   favicon-32.png          browser tab favicon
 *   favicon.ico             16+32 ICO bundle for legacy browsers
 *   apple-touch-icon.png    iOS Safari "Add to Home Screen" (180×180)
 *
 * Run with:  pnpm gen:icons
 * Run-when:  whenever icon.svg changes; the generated PNGs are committed.
 */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ICONS_DIR = path.resolve("public/icons");
const ICON_SVG = path.join(ICONS_DIR, "icon.svg");

const baseSvg = await readFile(ICON_SVG, "utf8");

// Maskable variant: drop the rounded-corner clip so the OS-applied mask never
// reveals transparent corners. The cream background covers the full 512×512.
const maskableSvg = baseSvg.replace(/\brx="108"/, 'rx="0"');

async function rasterize(svg, size, outName, { density } = {}) {
  await sharp(Buffer.from(svg), {
    density: density ?? Math.round((size / 512) * 384),
  })
    .resize(size, size, {
      fit: "contain",
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .png({ compressionLevel: 9 })
    .toFile(path.join(ICONS_DIR, outName));
  console.log(`  ✓ ${outName}  (${size}×${size})`);
}

console.log("Generating icons from", ICON_SVG);

await rasterize(baseSvg, 192, "icon-192.png");
await rasterize(baseSvg, 512, "icon-512.png");
await rasterize(maskableSvg, 512, "icon-maskable-512.png");
await rasterize(baseSvg, 180, "apple-touch-icon.png");
await rasterize(baseSvg, 32, "favicon-32.png");
await rasterize(baseSvg, 16, "favicon-16.png");

// favicon.ico — bundle 16+32 into a single ICO using sharp + manual ICO header
// is fiddly; ship a 32×32 .ico (sharp emits PNG-in-ICO via .toFormat("ico")).
await sharp(Buffer.from(baseSvg), { density: 96 })
  .resize(32, 32, { fit: "contain" })
  .toFormat("png")
  .toFile(path.join(ICONS_DIR, "favicon.png"));
console.log("  ✓ favicon.png  (32×32 — modern browsers use this)");

console.log("\nDone. Commit the regenerated PNGs.");

// Tiny prelude so a CI bot can grep for completion
await writeFile(
  path.join(ICONS_DIR, ".generated"),
  `# Generated by scripts/generate-icons.mjs at ${new Date().toISOString()}\n`,
);
